Replace fucntion is working now #1455
agershun/alasql pull request #1774
Opened 2023-08-15 08:04 UTC by NmN03jain

Thank you for the time you are putting into AlaSQL!

2023-08-15 08:43 UTC, mathiasrw requested changes
Please add a test file that verifies the bahavour so we dont accidentally break it at some point. 

Copy the test/test000.js to test/test1455.js and adapt the logic

2023-08-15 09:25 UTC, NmN03jain commented
@mathiasrw requested chages are made ,can you pls verify .

2023-08-15 14:31 UTC, NmN03jain commented
@mathiasrw what changes i need to performe ?

2023-08-16 11:34 UTC, mathiasrw commented
<img width="281" alt="image" src="https://github.com/AlaSQL/alasql/assets/1063454/b0ca46f1-0a9c-4831-9ed2-f29ec9f195f9">

Please insert a .toString() at the end of the value and make sure we dont throw an error.

2023-08-19 19:52 UTC, NmN03jain commented
@mathiasrw any more changes required ?

2023-09-05 19:00 UTC, mathiasrw commented
Yes. Please see the pending review changes

<img width="850" alt="image" src="https://github.com/AlaSQL/alasql/assets/1063454/57786fa1-4333-4c66-a767-033da61835ab">
<img width="855" alt="image" src="https://github.com/AlaSQL/alasql/assets/1063454/6e916937-900a-4f0c-a188-3342b2c78ac2">
<img width="843" alt="image" src="https://github.com/AlaSQL/alasql/assets/1063454/49a66734-7d31-4bf4-9562-1084494b03e7">

2023-09-06 19:01 UTC, mathiasrw commented
Please make sure that `npx yarn test` is working locally before pushing.

2023-11-09 14:36 UTC, mathiasrw commented
How can I help get the last little bits aligned?

2025-11-30 12:05 UTC, mathiasrw commented
Im lifting this in to help help solving the last little bits.

2025-11-30 12:05 UTC, merged