Update 15utility.js to improve readability.
agershun/alasql pull request #1878
Opened 2024-02-09 17:25 UTC by JoshuaPoon1

Edited utils.glob and utils.like to improve readability. Proved comments to help reader traverse through code. 

Also rename:
und ----> undefinedOrValue
n2u ——> nanToUndefined

Thank you for the time you are putting into AlaSQL!

2024-02-10 00:26 UTC, mathiasrw requested changes
Nice. I like it. Please have a look at the trivial comments and lets merge!

2024-02-10 00:26 UTC, mathiasrw commented on src/15utility.js
>  	return '(y=' + s + ',y===y?y:undefined)';
I like it. 

Just remove the comment.

2024-02-10 00:26 UTC, mathiasrw commented on src/15utility.js
> +	var currentIndex = 0; // Index for traversing the pattern string.
Looks good. You can also change var to let as you see fit.

2024-02-10 00:26 UTC, mathiasrw commented on src/15utility.js
> +  		      i++; // Skip next character as it's escaped.
Looks like its mixing spaces and tabs. Please run `npx yarn format-all`

2024-02-10 02:27 UTC, mathiasrw commented
also: please run `npx yarn test` locally to make sure tests are passing.

2024-02-11 23:15 UTC, JoshuaPoon1 commented on src/15utility.js
>  	return '(y=' + s + ',y===y?y:undefined)';
ok!

2024-07-11 21:10 UTC, mathiasrw commented
Im getting this error - any chance you can take a look?

```
Running tests on alasql@4.4.0

  Environment detected: {
    "alasqlPath": "/home/runner/work/alasql/alasql/dist",
    "isBrowser": false,
    "isCordova": false,
    "isMeteor": false,
    "isMeteorClient": false,
    "isMeteorServer": false,
    "isNode": true,
    "isWebWorker": false
}

 Exception during run: ReferenceError: n2u is not defined
    at /home/runner/work/alasql/alasql/dist/alasql.fs.js:9030:56
    at Array.forEach (<anonymous>)
    at Select.yy.Select.compileSelect1 (/home/runner/work/alasql/alasql/dist/alasql.fs.js:[8](https://github.com/AlaSQL/alasql/actions/runs/9898494687/job/27345441962?pr=1878#step:7:9)828:15)
    at Select.compile (/home/runner/work/alasql/alasql/dist/alasql.fs.js:7414:27)
    at Function.alasql.dexec (/home/runner/work/alasql/alasql/dist/alasql.fs.js:4765:38)
    at Function.alasql.exec (/home/runner/work/alasql/alasql/dist/alasql.fs.js:4720:17)
    at alasql (/home/runner/work/alasql/alasql/dist/alasql.fs.js:137:17)
    at /home/runner/work/alasql/alasql/test/test374.js:154:21
    at Array.forEach (<anonymous>)
    at Suite.<anonymous> (/home/runner/work/alasql/alasql/test/test374.js:140:5)
    at Object.create (/home/runner/work/alasql/alasql/node_modules/mocha/lib/interfaces/common.js:148:1[9](https://github.com/AlaSQL/alasql/actions/runs/9898494687/job/27345441962?pr=1878#step:7:10))
    at context.describe.context.context (/home/runner/work/alasql/alasql/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at Object.<anonymous> (/home/runner/work/alasql/alasql/test/test374.js:7:1)
    at Module._compile (node:internal/modules/cjs/loader:[10](https://github.com/AlaSQL/alasql/actions/runs/9898494687/job/27345441962?pr=1878#step:7:11)92:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:[11](https://github.com/AlaSQL/alasql/actions/runs/9898494687/job/27345441962?pr=1878#step:7:12)21:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:8[13](https://github.com/AlaSQL/alasql/actions/runs/9898494687/job/27345441962?pr=1878#step:7:14):14)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:201:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:154:23)
    at async Loader.import (node:internal/modules/esm/loader:177:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async formattedImport (/home/runner/work/alasql/alasql/node_modules/mocha/lib/nodejs/esm-utils.js:9:[14](https://github.com/AlaSQL/alasql/actions/runs/9898494687/job/27345441962?pr=1878#step:7:15))
    at async Object.exports.requireOrImport (/home/runner/work/alasql/alasql/node_modules/mocha/lib/nodejs/esm-utils.js:42:28)
    at async Object.exports.loadFilesAsync (/home/runner/work/alasql/alasql/node_modules/mocha/lib/nodejs/esm-utils.js:100:20)
    at async singleRun (/home/runner/work/alasql/alasql/node_modules/mocha/lib/cli/run-helpers.js:[15](https://github.com/AlaSQL/alasql/actions/runs/9898494687/job/27345441962?pr=1878#step:7:16)8:3)
    at async Object.exports.handler (/home/runner/work/alasql/alasql/node_modules/mocha/lib/cli/run.js:370:5)
error Command failed with exit code 1.
```

2024-12-15 03:35 UTC, mathiasrw commented
@JoshuaPoon1 ?

2025-11-30 12:14 UTC, mathiasrw commented
Lifting this in to get help sorting the last little bits.

2025-11-30 12:14 UTC, merged