Add jsonl support
agershun/alasql pull request #1919
Opened 2024-05-06 15:06 UTC by kfigiela

JSON support is great, but JSONL is very common in streaming cases (e.g. logs). 

```
$ cat test.jsonl
{"a": 1}
{"a": 2}
{"a": 42}

$ alasql "select * from jsonl('./test') where a > 1"
[
  {
    "a": 2
  },
  {
    "a": 42
  }
]
```

2024-05-07 14:39 UTC, mathiasrw commented
Any chance you can add a test file that confirms its working (so we detect if we break that later)?

Is `jsonl` the right name? What about ndjson (new line delimited json) or I have even seen `jsons` ?

2024-05-08 13:43 UTC, mathiasrw requested changes

2024-05-08 13:43 UTC, mathiasrw commented on src/84from.js
> +		if (res[res.length - 1] === '') {
It could be more than one line that is empty, or an empty line in the middle. I thin its also good to ignore lines with only space. I propose you add 

.map(line => line.trim()).filter(Boolean); to line 142 and remove line 144-146

2024-05-08 13:43 UTC, mathiasrw commented on src/84from.js
> +			res[i] = JSON.parse(res[i]);
Are we happy with a random error message, or should we provide more informative error message from a try-catch?

2024-05-17 03:35 UTC, mathiasrw commented
@kfigiela ?

2024-05-17 08:54 UTC, kfigiela commented
@mathiasrw, thanks for reminder. I'll try to address those over the weekend and add tests.

As far as the extension/naming, according to [a blog post](https://www.hypertesto.me/en/blog/jsonl-and-ndjson/) these are "competing", but practically identical standards. We only parse, so as long as JSON.parse can handle it we should be good. I think, it makes sense to register them both, so either file extension works.

2024-05-17 08:55 UTC, kfigiela commented on src/84from.js
> +			res[i] = JSON.parse(res[i]);
Right, enriching with line number can be super useful in case of invalid input.

2024-05-20 05:49 UTC, paulrutter commented
https://duckdb.org/2023/03/03/json.html uses ndjson indeed, would be good to rename.

2024-05-20 07:29 UTC, kfigiela commented
On the other hand, Google BigQuery mentions JSONL everywhere. Nevertheless, we can have both aliases working and this is what I have implemented. Otherwise, I addressed the above comments and added some tests.

2024-05-23 14:01 UTC, mathiasrw commented
Just provide all the most used names (alasql.jsonl = alasql.ndjson = alsql.....)

2024-05-23 14:02 UTC, mathiasrw commented
Ahh - you already did :)

2024-05-23 14:05 UTC, mathiasrw approved these changes

2024-05-23 14:05 UTC, mathiasrw commented on src/84from.js
>  	return res;
THanks

2024-05-23 14:21 UTC, mathiasrw commented
Doing a bit of performance testing. 

<img width="294" alt="image" src="https://github.com/AlaSQL/alasql/assets/1063454/7259f7a7-4f95-4f00-9349-a26f26c174c7">

its faster just to regex `\s*\r?\n\s*/` as it removes any empty lines in one swoop. Ill add this before merging.

2024-05-23 14:27 UTC, merged