Issue #1883 + Typescript Plugin Improvements
agershun/alasql pull request #1986
Opened 2024-11-05 23:44 UTC by Charlesnorris509

Key changes include using arrow functions and template literals for cleaner syntax, and optional chaining to streamline property access where values may be undefined. Destructured assignments enhance readability, and constants are used for immutability where applicable. Additionally, inline comments clarify each change for easy reference, while error handling improvements ensure the code remains robust and clear. These changes collectively modernize the codebase while preserving its original functionality and use cases

2024-12-01 02:06 UTC, mathiasrw commented
I love it. Thank you!

2024-12-01 09:56 UTC, mathiasrw requested changes
Please see comments.

2024-12-01 09:56 UTC, mathiasrw commented on src/56sprintf.js
> +// Regular expression updated with comments for readability
That comments?

2024-12-01 09:56 UTC, mathiasrw commented on src/56sprintf.js
> +	x[2] = x[2] === '-' ? '+' : '-'; // Adjust alignment for string output
Are you sure that comment is correct?

2024-12-01 09:56 UTC, mathiasrw commented on src/63createvertex.js
> +// Date: 04/11/2024
Please do not change the date.

2024-12-01 09:56 UTC, mathiasrw commented on src/63createvertex.js
> +// (c) 2015, Andrey Gershu
Please dont change the surname of the author...

2024-12-01 09:56 UTC, mathiasrw commented on src/63createvertex.js
> +yy.CreateVertex = (params) => Object.assign(this, params); // Updated to arrow function
Please dont leave comments like this as it will not make sense in the future

2024-12-01 09:56 UTC, mathiasrw commented on src/63createvertex.js
> +		s += `${this.class} `;
Please keep the original one as its more performant and does not help readability

2024-12-01 09:56 UTC, mathiasrw commented on src/63createvertex.js
> +	return `this.queriesfn[${this.queriesidx - 1}](this.params,null,${context})`; // Updated to template literal
I like the change. Please remove the comment.

2024-12-01 09:56 UTC, mathiasrw commented on src/63createvertex.js
> +	const dbid = databaseid; // Changed to const for immutability
Please remove the comment

2024-12-01 09:56 UTC, mathiasrw commented on src/63createvertex.js
> +	const sharp = this.sharp; // const for fixed ID reference
Please remove the comment

2024-12-01 09:56 UTC, mathiasrw commented on src/63createvertex.js
> -		// CREATE VERTEX without parameters
Can we keep this comment please?

2024-12-01 09:56 UTC, mathiasrw commented on src/63createvertex.js
> +		namefn?.(vertex); // Optional chaining for cleaner invocation
Please remove comment

2024-12-01 09:56 UTC, mathiasrw commented on src/63createvertex.js
> +yy.CreateEdge = (params) => Object.assign(this, params); // Updated to arrow function
Please remove comment

2024-12-01 09:56 UTC, mathiasrw commented on src/63createvertex.js
> +		s += `${this.class} `;
Please keep the original

2024-12-01 09:56 UTC, mathiasrw commented on src/63createvertex.js
> +	// Future TODOs: SET, CONTENT, SELECT
Please keep the original comments please

2024-12-01 09:56 UTC, mathiasrw commented on src/63createvertex.js
> +	return `this.queriesfn[${this.queriesidx - 1}](this.params,null,${context})`; // Template literal for consistency
Please remove comment

2024-12-01 09:56 UTC, mathiasrw commented on src/63createvertex.js
> +		namefn?.(edge); // Optional chaining
Please remove comment

2024-12-01 09:56 UTC, mathiasrw commented on src/63createvertex.js
> +			e.$id = e.$id ?? db.counter++;
Nice

2024-12-01 09:56 UTC, mathiasrw commented on src/63createvertex.js
> +		return Object.values(alasql.databases[alasql.useid].objects).find((obj) => obj.name === name);
We simply cant be making copies of all the data in an object for operations like this. We need to keep the original or find a way where we can search the original object without making a copy.

2024-12-01 09:56 UTC, mathiasrw requested changes
Please see comments.

2024-12-01 10:17 UTC, mathiasrw requested changes
We need comments to be related to what the code does (if needed at all) - not why something was changed.

2024-12-01 10:17 UTC, mathiasrw commented on src/63createvertex.js
> +		const v = {
Too many changes. And I dont feel like this will provide the same result. where. is the .prop aspect?

2024-12-01 10:17 UTC, mathiasrw commented on src/63createvertex.js
> -yy.CreateGraph.prototype.compile1 = function (databaseid) {
Did we just remove all of this?!?

2024-12-01 10:17 UTC, mathiasrw commented on src/76usedatabase.js
> +yy.CreateDatabase = (params) => Object.assign(this, params); // Updated to arrow function
Please keep regular functions for high level so they remain informative in the stack trace

2024-12-01 10:17 UTC, mathiasrw commented on src/76usedatabase.js
> +	let s = 'CREATE '; // Added space after 'CREATE' for clarity
Please revert comment

2024-12-01 10:17 UTC, mathiasrw commented on src/76usedatabase.js
> +	if (this.args?.length) { // Optional chaining for args presence check
Please remove comment

2024-12-01 10:17 UTC, mathiasrw commented on src/76usedatabase.js
> +	if (this.args?.length) { // Optional chaining and let for block scoping
Please remove comment

2024-12-01 10:17 UTC, mathiasrw commented on src/76usedatabase.js
> +		args = this.args.map(arg => new Function('params,alasql', `var y;return ${arg.toJS()}`)(params, alasql)); // Template literals for readability
Please remove comment

2024-12-01 10:17 UTC, mathiasrw commented on src/76usedatabase.js
> +		const dbInstance = new alasql.Database(dbid); // Renamed variable for clarity
Please remove comment

2024-12-01 10:17 UTC, mathiasrw commented on src/76usedatabase.js
> +yy.DetachDatabase = (params) => Object.assign(this, params); // Updated to arrow function
Please remove comment

2024-12-01 10:17 UTC, mathiasrw commented on src/76usedatabase.js
> +	return `DETACH DATABASE ${this.databaseid}`; // Template literal for consistency
Please remove comment

2024-12-01 10:17 UTC, mathiasrw commented on src/76usedatabase.js
> +	if (!alasql.databases[this.databaseid]?.engineid) {
Please remove comment

2024-12-01 10:17 UTC, mathiasrw commented on src/76usedatabase.js
> +		throw new Error(`Cannot detach database "${this.databaseid}", because it was not attached.`); // Updated error message
Please remove comment

2024-12-01 10:17 UTC, mathiasrw commented on src/76usedatabase.js
> -		// Usually databases are detached and then dropped. Detaching will delete
Please keep comment for context

2024-12-01 10:17 UTC, mathiasrw commented on src/76usedatabase.js
> -			// Create a detached FS database
Please keep comment

2024-12-01 10:17 UTC, mathiasrw commented on src/76usedatabase.js
> +yy.UseDatabase = (params) => Object.assign(this, params); // Updated to arrow function
Please remove comment

2024-12-01 10:17 UTC, mathiasrw commented on src/76usedatabase.js
> +	return `USE DATABASE ${this.databaseid}`; // Template literal for consistency
Please remove comment

2024-12-01 10:17 UTC, mathiasrw commented on src/76usedatabase.js
> +yy.DropDatabase = (params) => Object.assign(this, params); // Updated to arrow function
Please remove comment

2024-12-01 10:17 UTC, mathiasrw commented on src/76usedatabase.js
> +	const dbInstance = alasql.databases[dbid]; // Renamed for clarity
Please remove comment

2024-12-01 10:17 UTC, mathiasrw commented on types/alasql.d.ts
> -	// https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/es6-promise/es6-promise.d.ts
Did we just remove all of this?!?

2024-12-01 10:17 UTC, mathiasrw commented on types/alasql.d.ts
> -	// see https://github.com/alasql/alasql/wiki/User%20Defined%20Functions
Please keep references like this

2024-12-01 10:17 UTC, mathiasrw commented on types/alasql.d.ts
> +	 * AlaSQL database object - a lightweight database implementation.
the comment is no longer accurate

2024-12-01 10:17 UTC, mathiasrw commented on types/alasql.d.ts
> +		 * Database identifier.
Is there no benefit in the old notation?

2024-12-01 10:17 UTC, mathiasrw commented on types/alasql.d.ts
> +		 * Collection of tables in the database.
Why was this comment updated?

2024-12-01 10:17 UTC, mathiasrw commented on types/alasql.d.ts
> +		 * Array of data rows within the table.
No value in the old comment?

2024-12-01 10:17 UTC, mathiasrw commented on types/alasql.d.ts
> +		 * Dictionary of databases managed by AlaSQL.
Why not the type notation?

2024-12-01 10:17 UTC, mathiasrw commented on types/alasql.d.ts
> +		 * Switches the current database context.
Please keep the context of the old comment

2024-12-01 10:17 UTC, mathiasrw commented on types/alasql.d.ts
> +		 * Current active database ID. Defaults to 'alasql' if none specified.
Why remove the type notation

2024-12-01 10:21 UTC, mathiasrw commented
Looks like the tests are not running. Please make sure to do a `yarn format` and then `yarn test` locally before you make a PR

2024-12-15 03:45 UTC, mathiasrw commented
@Charlesnorris509 ?

2024-12-26 21:42 UTC, Charlesnorris509 commented on src/63createvertex.js
> +yy.CreateVertex = (params) => Object.assign(this, params); // Updated to arrow function
Thanks for letting me know and sorry for the late reply

2024-12-26 21:50 UTC, Charlesnorris509 reviewed
Thank you foor the reviews and comments Ill make the necessary changes

2025-01-14 01:12 UTC, closed without merging